# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '33462745-dd5a-4517-afab-3468f9bec5ac'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMTemplateLab1'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureLabs1 -linkedTemplateUri https://raw.githubusercontent.com/guerra41/AzureRmPipeline-repo/master/CreateWebApp/linkedStorageAccount.json?token=AANBXBKLBLO2RLSXKPCOJJK6XT35G'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
